import { useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import {
  notificationService,
  type NotificationsListParams,
} from "@/services/notification.service";

const NOTIFICATIONS_KEY = "notifications";

export function useNotifications(params: NotificationsListParams = {}) {
  return useQuery({
    queryKey: [NOTIFICATIONS_KEY, params],
    queryFn: () => notificationService.list(params),
    staleTime: 10_000,
    // Polled, not just fetched on mount — same reasoning as Modules'
    // institution polling: a notification generated by someone else's
    // action should reach an already-open session without a refresh, and
    // this is too infrequent an event to justify a push/WebSocket layer.
    refetchInterval: 15_000,
  });
}

export function useUnreadCount() {
  return useQuery({
    queryKey: [NOTIFICATIONS_KEY, "unread-count"],
    queryFn: () => notificationService.unreadCount(),
    staleTime: 10_000,
    refetchInterval: 15_000,
  });
}

export function useMarkNotificationRead() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => notificationService.markRead(id),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: [NOTIFICATIONS_KEY] }),
  });
}

export function useMarkAllNotificationsRead() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => notificationService.markAllRead(),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: [NOTIFICATIONS_KEY] }),
  });
}

export function useDismissNotification() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => notificationService.dismiss(id),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: [NOTIFICATIONS_KEY] }),
  });
}

export type NotificationItem = {
  id: string;
  title: string;
  message: string;
  href?: string;
  createdAt: string;
  read: boolean;
};

/**
 * The full notifications feed for the current caller — entirely backend-real
 * (Institutions/User Manager/Modules/License Manager, API_CONTRACT.md §10),
 * already scoped server-side to what that caller can see (platform-wide for
 * super_admin, institution + personal for institution_admin). No local/mock
 * data on either side (2026-09-26, explicitly requested — "no mock or
 * hardcoded data for notifications, for either role"): a domain that still
 * has no backend of its own (Students/Staff/Academic Sessions/etc.) simply
 * produces no notifications yet, rather than a fabricated local one.
 */
export function useNotificationsFeed() {
  const { data, isLoading } = useNotifications({ perPage: 100 });

  const notifications = useMemo<NotificationItem[]>(
    () =>
      [...(data?.data ?? [])].sort((a, b) =>
        b.createdAt.localeCompare(a.createdAt),
      ),
    [data],
  );

  return { notifications, isLoading };
}
