package com.teducare.student;

import java.time.Instant;

public record StudentResponse(
        String id,
        String matricNo,
        String title,
        String firstName,
        String middleName,
        String lastName,
        String otherName,
        String gender,
        String maritalStatus,
        String email,
        String phone,
        String emergencyContact,
        Instant dateOfBirth,
        String religion,
        String maidenName,
        String bloodGroup,
        String genotype,
        double weightKg,
        double heightCm,
        String nationality,
        String stateOfOrigin,
        String lga,
        String residentAddress,
        String avatarUrl,
        String schoolId,
        String facultyId,
        String departmentId,
        String programId,
        String programLevelId,
        String currentSessionId,
        String status,
        boolean isGraduating,
        boolean isDeferred,
        boolean holdForReview,
        String disciplinaryStatus,
        String hostelName,
        String roomNumber,
        String allergies,
        String chronicConditions,
        String currentMedications,
        String pastSurgeries,
        String physicianName,
        String physicianPhone,
        String healthInsuranceProvider,
        String healthInsuranceNumber,
        String medicalNotes,
        Instant createdAt,
        Instant archivedAt) {

    static StudentResponse from(Student s) {
        return new StudentResponse(
                s.getId(),
                s.getMatricNo(),
                s.getTitle(),
                s.getFirstName(),
                s.getMiddleName(),
                s.getLastName(),
                s.getOtherName(),
                s.getGender(),
                s.getMaritalStatus(),
                s.getEmail(),
                s.getPhone(),
                s.getEmergencyContact(),
                s.getDateOfBirth(),
                s.getReligion(),
                s.getMaidenName(),
                s.getBloodGroup(),
                s.getGenotype(),
                s.getWeightKg(),
                s.getHeightCm(),
                s.getNationality(),
                s.getStateOfOrigin(),
                s.getLga(),
                s.getResidentAddress(),
                s.getAvatarUrl(),
                s.getSchoolId(),
                s.getFacultyId(),
                s.getDepartmentId(),
                s.getProgramId(),
                s.getProgramLevelId(),
                s.getCurrentSessionId(),
                s.getStatus(),
                s.isGraduating(),
                s.isDeferred(),
                s.isHoldForReview(),
                s.getDisciplinaryStatus(),
                s.getHostelName(),
                s.getRoomNumber(),
                s.getAllergies(),
                s.getChronicConditions(),
                s.getCurrentMedications(),
                s.getPastSurgeries(),
                s.getPhysicianName(),
                s.getPhysicianPhone(),
                s.getHealthInsuranceProvider(),
                s.getHealthInsuranceNumber(),
                s.getMedicalNotes(),
                s.getCreatedAt(),
                s.getArchivedAt());
    }
}
