package com.teducare.student;

import java.time.Instant;

/** Any field left null keeps its current value — same partial-update convention as program/UpdateProgramRequest. Booleans use boxed `Boolean` for the same reason. */
public record UpdateStudentRequest(
        String matricNo,
        String jambRegNumber,
        String admissionMode,
        String title,
        String firstName,
        String middleName,
        String lastName,
        String otherName,
        String gender,
        String maritalStatus,
        String email,
        String phone,
        String emergencyContact,
        Instant dateOfBirth,
        String religion,
        String maidenName,
        String bloodGroup,
        String genotype,
        Double weightKg,
        Double heightCm,
        String nationality,
        String stateOfOrigin,
        String lga,
        String residentAddress,
        String avatarUrl,
        String schoolId,
        String facultyId,
        String departmentId,
        String programId,
        String programLevelId,
        String currentSessionId,
        String status,
        Boolean isGraduating,
        Boolean isDeferred,
        Boolean holdForReview,
        String hostelName,
        String roomNumber,
        String allergies,
        String chronicConditions,
        String currentMedications,
        String pastSurgeries,
        String physicianName,
        String physicianPhone,
        String healthInsuranceProvider,
        String healthInsuranceNumber,
        String medicalNotes) {
}
