import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { Institution } from "@/types/institution";

function makeId() {
  return `inst-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function makeTokenKey() {
  return Array.from({ length: 4 }, () =>
    Math.random().toString(36).slice(2, 6).toUpperCase(),
  ).join("-");
}

const SEEDED_INSTITUTIONS: Institution[] = [
  {
    id: "inst-xyz-college",
    code: "001",
    name: "XYZ College of Technology",
    institutionType: "University",
    address: "12 Independence Way",
    city: "Owerri",
    countryState: "Nigeria - Imo State",
    principalName: "Mr John Bassey",
    principalEmail: "john.bassey@xyzcollege.edu.ng",
    principalPhone: "08031234567",
    adminUser: "James Keen",
    adminEmail: "james.keen@xyzcollege.edu.ng",
    modulesCount: 10,
    studentCount: 90,
    revenue: 120000,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "TK4F-8H2K-9P1Q-XZ3M",
    status: "active",
    createdAt: "2026-03-03T14:32:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-babcock",
    code: "002",
    name: "Babcock University",
    institutionType: "University",
    address: "PMB 4003",
    city: "Ilishan-Remo",
    countryState: "Nigeria - Ogun State",
    principalName: "Mr Chris Smart",
    principalEmail: "chris-smart@gmail.com",
    principalPhone: "08025771099",
    adminUser: "Solomon Akpo",
    adminEmail: "solomon.odogun@gmail.com",
    modulesCount: 6,
    studentCount: 70,
    revenue: 85000,
    licenseType: "Premium",
    expiringAt: "2027-03-03T00:00:00.000Z",
    tokenKey: "TK7B-2N5R-6V8W-LQ1D",
    status: "active",
    createdAt: "2026-03-03T11:13:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-ibadan",
    code: "003",
    name: "University of Ibadan",
    institutionType: "University",
    address: "Ibadan-Ife Road",
    city: "Ibadan",
    countryState: "Nigeria - Oyo State",
    principalName: "Mrs Funmi Adeyemi",
    principalEmail: "funmi.adeyemi@ui.edu.ng",
    principalPhone: "08039876543",
    adminUser: "Stanly Hip",
    adminEmail: "stanly.hip@ui.edu.ng",
    modulesCount: 8,
    studentCount: 50,
    revenue: 50000,
    licenseType: "Premium",
    expiringAt: "2027-03-03T00:00:00.000Z",
    tokenKey: "TK2Y-9J4C-3E7T-RM6S",
    status: "inactive",
    createdAt: "2026-03-03T09:15:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-universityoflagos-0",
    code: "004",
    name: "University of Lagos",
    institutionType: "University",
    address: "10 Independence Way",
    city: "Lagos",
    countryState: "Nigeria - Lagos State",
    principalName: "Prof. Amara Okafor",
    principalEmail: "amara.okafor@universityofla.edu.ng",
    principalPhone: "08030000000",
    adminUser: "James Akpo",
    adminEmail: "james.akpo@universityofla.edu.ng",
    modulesCount: 4,
    studentCount: 30,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "0V6U-E6JB-PL25-D1ZC",
    status: "active",
    createdAt: "2026-03-03T07:00:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-ahmadubellouniversit-1",
    code: "005",
    name: "Ahmadu Bello University",
    institutionType: "University",
    address: "11 University Road",
    city: "Zaria",
    countryState: "Nigeria - Kaduna State",
    principalName: "Prof. Tunde Ogundele",
    principalEmail: "tunde.ogundele@ahmadubellouni.edu.ng",
    principalPhone: "08031234567",
    adminUser: "Solomon Okafor",
    adminEmail: "solomon.okafor@ahmadubellouni.edu.ng",
    modulesCount: 5,
    studentCount: 47,
    revenue: 43300,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "REZL-R88N-L1KD-GW3X",
    status: "active",
    createdAt: "2026-03-03T08:07:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-obafemiawolowouniver-2",
    code: "006",
    name: "Obafemi Awolowo University",
    institutionType: "University",
    address: "12 Campus Drive",
    city: "Ile-Ife",
    countryState: "Nigeria - Osun State",
    principalName: "Prof. Bisi Yusuf",
    principalEmail: "bisi.yusuf@obafemiawolowo.edu.ng",
    principalPhone: "08032469134",
    adminUser: "Stanly Adeyemi",
    adminEmail: "stanly.adeyemi@obafemiawolowo.edu.ng",
    modulesCount: 6,
    studentCount: 64,
    revenue: 46600,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "G0SD-3BXZ-GH1N-KQ7H",
    status: "active",
    createdAt: "2026-03-03T09:14:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-universityofnigerian-3",
    code: "007",
    name: "University of Nigeria, Nsukka",
    institutionType: "University",
    address: "13 Ring Road",
    city: "Nsukka",
    countryState: "Nigeria - Enugu State",
    principalName: "Prof. Kemi Adamu",
    principalEmail: "kemi.adamu@universityofni.edu.ng",
    principalPhone: "08033703701",
    adminUser: "Ngozi Adamu",
    adminEmail: "ngozi.adamu@universityofni.edu.ng",
    modulesCount: 7,
    studentCount: 81,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "7KK5-FELA-DZJW-NKB3",
    status: "active",
    createdAt: "2026-03-03T10:21:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-lagosstateuniversity-4",
    code: "008",
    name: "Lagos State University",
    institutionType: "University",
    address: "14 Airport Road",
    city: "Ojo",
    countryState: "Nigeria - Lagos State",
    principalName: "Prof. Femi Okon",
    principalEmail: "femi.okon@lagosstateuniv.edu.ng",
    principalPhone: "08034938268",
    adminUser: "Chidi Ibrahim",
    adminEmail: "chidi.ibrahim@lagosstateuniv.edu.ng",
    modulesCount: 8,
    studentCount: 98,
    revenue: 53200,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "Y4CY-THAM-9E14-REEP",
    status: "active",
    createdAt: "2026-03-03T11:28:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-federaluniversityoft-5",
    code: "009",
    name: "Federal University of Technology, Akure",
    institutionType: "University",
    address: "15 Independence Way",
    city: "Akure",
    countryState: "Nigeria - Ondo State",
    principalName: "Prof. Hauwa Danjuma",
    principalEmail: "hauwa.danjuma@federalunivers.edu.ng",
    principalPhone: "08036172835",
    adminUser: "Amara Adeleke",
    adminEmail: "amara.adeleke@federalunivers.edu.ng",
    modulesCount: 9,
    studentCount: 115,
    revenue: 56500,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "PQ5R-5LZY-6WHC-U9J8",
    status: "inactive",
    createdAt: "2026-03-03T12:35:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-nnamdiazikiweunivers-6",
    code: "010",
    name: "Nnamdi Azikiwe University",
    institutionType: "University",
    address: "16 University Road",
    city: "Awka",
    countryState: "Nigeria - Anambra State",
    principalName: "Prof. Yusuf Adeleke",
    principalEmail: "yusuf.adeleke@nnamdiazikiweu.edu.ng",
    principalPhone: "08037407402",
    adminUser: "Tunde Ajayi",
    adminEmail: "tunde.ajayi@nnamdiazikiweu.edu.ng",
    modulesCount: 10,
    studentCount: 132,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "E9YH-GNP9-2C0L-X4NU",
    status: "active",
    createdAt: "2026-03-03T13:42:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-bayerouniversitykano-7",
    code: "011",
    name: "Bayero University Kano",
    institutionType: "University",
    address: "17 Campus Drive",
    city: "Kano",
    countryState: "Nigeria - Kano State",
    principalName: "Prof. Emeka Okoro",
    principalEmail: "emeka.okoro@bayerouniversi.edu.ng",
    principalPhone: "08038641969",
    adminUser: "Bisi Nnamdi",
    adminEmail: "bisi.nnamdi@bayerouniversi.edu.ng",
    modulesCount: 11,
    studentCount: 149,
    revenue: 63100,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "5URA-URCK-ZTGV-0ZSE",
    status: "active",
    createdAt: "2026-03-03T14:49:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-universityofbenin-8",
    code: "012",
    name: "University of Benin",
    institutionType: "University",
    address: "18 Ring Road",
    city: "Benin City",
    countryState: "Nigeria - Edo State",
    principalName: "Prof. Ifeoma Suleiman",
    principalEmail: "ifeoma.suleiman@universityofbe.edu.ng",
    principalPhone: "08039876536",
    adminUser: "Kemi Akpo",
    adminEmail: "kemi.akpo@universityofbe.edu.ng",
    modulesCount: 12,
    studentCount: 166,
    revenue: 66400,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "WEJ2-6U2W-V9Z3-3UW0",
    status: "active",
    createdAt: "2026-03-03T15:56:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-riversstateuniversit-9",
    code: "013",
    name: "Rivers State University",
    institutionType: "University",
    address: "19 Airport Road",
    city: "Port Harcourt",
    countryState: "Nigeria - Rivers State",
    principalName: "Prof. Grace Nnamdi",
    principalEmail: "grace.nnamdi@riversstateuni.edu.ng",
    principalPhone: "08041111103",
    adminUser: "Femi Okafor",
    adminEmail: "femi.okafor@riversstateuni.edu.ng",
    modulesCount: 4,
    studentCount: 183,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "MZBV-JXR7-SQFB-6PZK",
    status: "active",
    createdAt: "2026-03-03T16:03:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-deltastateuniversity-10",
    code: "014",
    name: "Delta State University",
    institutionType: "University",
    address: "20 Independence Way",
    city: "Abraka",
    countryState: "Nigeria - Delta State",
    principalName: "Prof. Peter Keen",
    principalEmail: "peter.keen@deltastateuniv.edu.ng",
    principalPhone: "08042345670",
    adminUser: "Hauwa Adeyemi",
    adminEmail: "hauwa.adeyemi@deltastateuniv.edu.ng",
    modulesCount: 5,
    studentCount: 200,
    revenue: 73000,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "CJ4N-WZFJ-P6YK-9H35",
    status: "active",
    createdAt: "2026-03-03T07:10:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-yabacollegeoftechnol-11",
    code: "015",
    name: "Yaba College of Technology",
    institutionType: "Polytechnic",
    address: "21 University Road",
    city: "Yaba",
    countryState: "Nigeria - Lagos State",
    principalName: "Prof. Ruth Hip",
    principalEmail: "ruth.hip@yabacollegeoft.edu.ng",
    principalPhone: "08043580237",
    adminUser: "Yusuf Adamu",
    adminEmail: "yusuf.adamu@yabacollegeoft.edu.ng",
    modulesCount: 6,
    studentCount: 217,
    revenue: 76300,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "34XE-724V-KNFT-CC7R",
    status: "inactive",
    createdAt: "2026-03-03T08:17:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-federalpolytechnicil-12",
    code: "016",
    name: "Federal Polytechnic, Ilaro",
    institutionType: "Polytechnic",
    address: "22 Campus Drive",
    city: "Ilaro",
    countryState: "Nigeria - Ogun State",
    principalName: "Prof. David Okafor",
    principalEmail: "david.okafor@federalpolytec.edu.ng",
    principalPhone: "08044814804",
    adminUser: "Emeka Ibrahim",
    adminEmail: "emeka.ibrahim@federalpolytec.edu.ng",
    modulesCount: 7,
    studentCount: 234,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "UPQ7-K5U6-G3X1-G7BB",
    status: "active",
    createdAt: "2026-03-03T09:24:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-kadunapolytechnic-13",
    code: "017",
    name: "Kaduna Polytechnic",
    institutionType: "Polytechnic",
    address: "23 Ring Road",
    city: "Kaduna",
    countryState: "Nigeria - Kaduna State",
    principalName: "Prof. Blessing Ogundele",
    principalEmail: "blessing.ogundele@kadunapolytech.edu.ng",
    principalPhone: "08046049371",
    adminUser: "Ifeoma Adeleke",
    adminEmail: "ifeoma.adeleke@kadunapolytech.edu.ng",
    modulesCount: 8,
    studentCount: 251,
    revenue: 82900,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "K8HZ-X8HH-CKEA-K2FX",
    status: "active",
    createdAt: "2026-03-03T10:31:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-auchipolytechnic-14",
    code: "018",
    name: "Auchi Polytechnic",
    institutionType: "Polytechnic",
    address: "24 Airport Road",
    city: "Auchi",
    countryState: "Nigeria - Edo State",
    principalName: "Prof. Michael Yusuf",
    principalEmail: "michael.yusuf@auchipolytechn.edu.ng",
    principalPhone: "08047283938",
    adminUser: "Grace Ajayi",
    adminEmail: "grace.ajayi@auchipolytechn.edu.ng",
    modulesCount: 9,
    studentCount: 268,
    revenue: 86200,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "AUAS-9B7U-90WJ-NXJG",
    status: "active",
    createdAt: "2026-03-03T11:38:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-federalcollegeofeduc-15",
    code: "019",
    name: "Federal College of Education, Zaria",
    institutionType: "College",
    address: "25 Independence Way",
    city: "Zaria",
    countryState: "Nigeria - Kaduna State",
    principalName: "Prof. Aisha Adamu",
    principalEmail: "aisha.adamu@federalcollege.edu.ng",
    principalPhone: "08048518505",
    adminUser: "Peter Nnamdi",
    adminEmail: "peter.nnamdi@federalcollege.edu.ng",
    modulesCount: 10,
    studentCount: 285,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "1D3J-MDW4-5GDS-RSN2",
    status: "active",
    createdAt: "2026-03-03T12:45:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-adeyemicollegeofeduc-16",
    code: "020",
    name: "Adeyemi College of Education",
    institutionType: "College",
    address: "26 University Road",
    city: "Ondo",
    countryState: "Nigeria - Ondo State",
    principalName: "Prof. Bola Okon",
    principalEmail: "bola.okon@adeyemicollege.edu.ng",
    principalPhone: "08049753072",
    adminUser: "Ruth Akpo",
    adminEmail: "ruth.akpo@adeyemicollege.edu.ng",
    modulesCount: 11,
    studentCount: 302,
    revenue: 92800,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "SYWB-YGKF-2YV0-UMSN",
    status: "active",
    createdAt: "2026-03-03T13:52:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-redeemersuniversity-17",
    code: "021",
    name: "Redeemer's University",
    institutionType: "University",
    address: "27 Campus Drive",
    city: "Ede",
    countryState: "Nigeria - Osun State",
    principalName: "Prof. Segun Danjuma",
    principalEmail: "segun.danjuma@redeemersunive.edu.ng",
    principalPhone: "08050987639",
    adminUser: "David Okafor",
    adminEmail: "david.okafor@redeemersunive.edu.ng",
    modulesCount: 12,
    studentCount: 319,
    revenue: 96100,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "HJP4-AK9S-YDC8-XGW8",
    status: "inactive",
    createdAt: "2026-03-03T14:59:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-afebabalolauniversit-18",
    code: "022",
    name: "Afe Babalola University",
    institutionType: "University",
    address: "28 Ring Road",
    city: "Ado-Ekiti",
    countryState: "Nigeria - Ekiti State",
    principalName: "Prof. Chinwe Adeleke",
    principalEmail: "chinwe.adeleke@afebabalolauni.edu.ng",
    principalPhone: "08052222206",
    adminUser: "Blessing Adeyemi",
    adminEmail: "blessing.adeyemi@afebabalolauni.edu.ng",
    modulesCount: 4,
    studentCount: 336,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "83GW-NNY3-VVVH-0A0T",
    status: "active",
    createdAt: "2026-03-03T15:06:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-landmarkuniversity-19",
    code: "023",
    name: "Landmark University",
    institutionType: "University",
    address: "29 Airport Road",
    city: "Omu-Aran",
    countryState: "Nigeria - Kwara State",
    principalName: "Prof. James Okoro",
    principalEmail: "james.okoro@landmarkuniver.edu.ng",
    principalPhone: "08053456773",
    adminUser: "Michael Adamu",
    adminEmail: "michael.adamu@landmarkuniver.edu.ng",
    modulesCount: 5,
    studentCount: 353,
    revenue: 102700,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "ZN9P-0QNE-RBBR-353D",
    status: "active",
    createdAt: "2026-03-03T16:13:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-bellsuniversityoftec-20",
    code: "024",
    name: "Bells University of Technology",
    institutionType: "University",
    address: "30 Independence Way",
    city: "Ota",
    countryState: "Nigeria - Ogun State",
    principalName: "Prof. Solomon Suleiman",
    principalEmail: "solomon.suleiman@bellsuniversit.edu.ng",
    principalPhone: "08054691340",
    adminUser: "Aisha Ibrahim",
    adminEmail: "aisha.ibrahim@bellsuniversit.edu.ng",
    modulesCount: 6,
    studentCount: 370,
    revenue: 106000,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "Q82F-CTBR-NSUZ-607Z",
    status: "active",
    createdAt: "2026-03-03T07:20:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-crawforduniversity-21",
    code: "025",
    name: "Crawford University",
    institutionType: "University",
    address: "31 University Road",
    city: "Faith Academy Rd, Ogun",
    countryState: "Nigeria - Ogun State",
    principalName: "Prof. Stanly Nnamdi",
    principalEmail: "stanly.nnamdi@crawforduniver.edu.ng",
    principalPhone: "08055925907",
    adminUser: "Bola Adeleke",
    adminEmail: "bola.adeleke@crawforduniver.edu.ng",
    modulesCount: 7,
    studentCount: 387,
    revenue: 0,
    licenseType: "Freemium",
    expiringAt: null,
    tokenKey: "FTV8-PW12-J8A7-9VBK",
    status: "active",
    createdAt: "2026-03-03T08:27:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-calebuniversity-22",
    code: "026",
    name: "Caleb University",
    institutionType: "University",
    address: "32 Campus Drive",
    city: "Imota, Lagos",
    countryState: "Nigeria - Lagos State",
    principalName: "Prof. Ngozi Keen",
    principalEmail: "ngozi.keen@calebuniversit.edu.ng",
    principalPhone: "08057160474",
    adminUser: "Segun Ajayi",
    adminEmail: "segun.ajayi@calebuniversit.edu.ng",
    modulesCount: 8,
    studentCount: 404,
    revenue: 112600,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "6CN1-1ZQD-FPTF-CQF4",
    status: "active",
    createdAt: "2026-03-03T09:34:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-nileuniversityofnige-23",
    code: "027",
    name: "Nile University of Nigeria",
    institutionType: "University",
    address: "33 Ring Road",
    city: "Abuja",
    countryState: "Nigeria - FCT Abuja",
    principalName: "Prof. Chidi Hip",
    principalEmail: "chidi.hip@nileuniversity.edu.ng",
    principalPhone: "08058395041",
    adminUser: "Chinwe Nnamdi",
    adminEmail: "chinwe.nnamdi@nileuniversity.edu.ng",
    modulesCount: 9,
    studentCount: 421,
    revenue: 115900,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "XYFT-D2EP-B59P-FKKQ",
    status: "inactive",
    createdAt: "2026-03-03T10:41:00.000Z",
    archivedAt: null,
  },
  {
    id: "inst-madonnauniversity-24",
    code: "028",
    name: "Madonna University",
    institutionType: "University",
    address: "34 University Road",
    city: "Okija",
    countryState: "Nigeria - Anambra State",
    principalName: "Prof. Uche Bassey",
    principalEmail: "uche.bassey@madonnauniversity.edu.ng",
    principalPhone: "08059406152",
    adminUser: "Solomon Okafor",
    adminEmail: "solomon.okafor@madonnauniversity.edu.ng",
    modulesCount: 6,
    studentCount: 274,
    revenue: 68300,
    licenseType: "Premium",
    expiringAt: "2027-03-02T23:00:00.000Z",
    tokenKey: "M4ND-0NN4-UN1V-9K2P",
    status: "active",
    createdAt: "2026-03-03T11:49:00.000Z",
    archivedAt: null,
  },
];

interface InstitutionsState {
  institutions: Institution[];
  createInstitution: (
    institution: Omit<
      Institution,
      "id" | "code" | "createdAt" | "tokenKey" | "archivedAt"
    >,
  ) => Institution;
  updateInstitution: (id: string, patch: Partial<Institution>) => void;
  archiveInstitution: (id: string) => void;
  restoreInstitution: (id: string) => void;
}

export const useInstitutionsStore = create<InstitutionsState>()(
  persist(
    (set, get) => ({
      institutions: SEEDED_INSTITUTIONS,

      createInstitution: (institution) => {
        const nextCode = String(get().institutions.length + 1).padStart(3, "0");
        const newInstitution: Institution = {
          ...institution,
          id: makeId(),
          code: nextCode,
          tokenKey: makeTokenKey(),
          createdAt: new Date().toISOString(),
          archivedAt: null,
        };
        set((state) => ({
          institutions: [newInstitution, ...state.institutions],
        }));
        return newInstitution;
      },

      updateInstitution: (id, patch) => {
        set((state) => ({
          institutions: state.institutions.map((institution) =>
            institution.id === id ? { ...institution, ...patch } : institution,
          ),
        }));
      },

      archiveInstitution: (id) => {
        set((state) => ({
          institutions: state.institutions.map((institution) =>
            institution.id === id
              ? { ...institution, archivedAt: new Date().toISOString() }
              : institution,
          ),
        }));
      },

      restoreInstitution: (id) => {
        set((state) => ({
          institutions: state.institutions.map((institution) =>
            institution.id === id
              ? { ...institution, archivedAt: null }
              : institution,
          ),
        }));
      },
    }),
    {
      name: "t-educare-institutions",
      version: 1,
      // No real migration path — this is mock data standing in for a real
      // API (see frontend/CLAUDE.md), so a version bump just means "discard
      // whatever shape was cached and reseed" rather than transform it field
      // by field. Providing this avoids zustand's noisy console.error (which
      // Next's dev overlay surfaces as a blocking-looking error) on mismatch.
      migrate: () => ({ institutions: SEEDED_INSTITUTIONS }),
    },
  ),
);
